# Generated by Django 4.0.2 on 2022-02-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='nme',
            new_name='name',
        ),
    ]
